elasticsearch:
  host: http://localhost:9200
  index_name: financial
  mapping: transaction

tags:
  rent:
    - Real State Co.
  shopping:
    - El corte ingles
  work:
    - Github
    - Amazon Web Services

parsers:
  ing: \Bank\Parser\Ing
  lacaixa: \Bank\Parser\LaCaixa